Default: &defaults
  database: develcputest.sqlite3
  poolsize: 10

Development:
  <<: *defaults

Testing:
  database: develcputest_test.sqlite3
  <<: *defaults

Staging:
  database: develcputest_staging.sqlite3
  poolsize: 100
  <<: *defaults

Production:
  database: develcputest_production.sqlite3
  poolsize: 100
  <<: *defaults
